language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

before_script:
    - travis_retry composer update --no-interaction

script:
    - vendor/bin/phpunit --testsuite tests
    - vendor/bin/phpunit --coverage-clover=./tests/report/coverage.clover
