version: '3'

services:
    composer:
        image: graze/composer
        volumes:
            - .:/usr/src/app
            - ~/.composer:/home/composer/.composer

    php:
        image: php:alpine
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
