version: '3'

services:
  db:
    image: mysql:5.6
    volumes:
      - ./example/schema:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=morphism-test
      - MYSQL_USER=morphism
      - MYSQL_PASSWORD=morphism
      - MYSQL_ROOT_PASSWORD=morphism

  morphism:
    image: graze/php-alpine:7.2
    volumes:
      - .:/srv
    entrypoint:
      - /srv/bin/morphism
